package com.newsMS.dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.java
//  @ Date : 2017-4-17
//  @ Author : 
//
//




/** */
public class Admin extends Person {
    /** */
    public int adminId;
    
    /** */
    public int actor;
    
    /** */
    public String department;

	/**
	 * @return the adminId
	 */
	public int getAdminId() {
		return adminId;
	}

	/**
	 * @param adminId the adminId to set
	 */
	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

	/**
	 * @return the actor
	 */
	public int getActor() {
		return actor;
	}

	/**
	 * @param actor the actor to set
	 */
	public void setActor(int actor) {
		this.actor = actor;
	}

	/**
	 * @return the department
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * @param department the department to set
	 */
	public void setDepartment(String department) {
		this.department = department;
	}
    
    /** */
    
    
    
    
}
