package com.newsMS.dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Category.java
//  @ Date : 2017-4-17
//  @ Author : 
//
//




/** */
public class Category {
    /** */
    public int categoryId;
    
    /** */
    public String categoryName;
    
    /** */
    public String categoryDetail;
    
    /** */
    public String note;

	/**
	 * @return the categoryId
	 */
	public int getCategoryId() {
		return categoryId;
	}

	/**
	 * @param categoryId the categoryId to set
	 */
	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * @return the categoryName
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * @param categoryName the categoryName to set
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * @return the categoryDetail
	 */
	public String getCategoryDetail() {
		return categoryDetail;
	}

	/**
	 * @param categoryDetail the categoryDetail to set
	 */
	public void setCategoryDetail(String categoryDetail) {
		this.categoryDetail = categoryDetail;
	}

	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}

	/**
	 * @param note the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}
    

    
    
}
